# Generated by Django 5.0.2 on 2024-03-25 13:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='姓名')),
                ('pid', models.CharField(max_length=255, verbose_name='身份证号')),
                ('birth', models.CharField(max_length=255, verbose_name='出生日期')),
                ('birth_address', models.CharField(max_length=255, verbose_name='籍贯')),
                ('age', models.CharField(max_length=255, verbose_name='年龄')),
                ('gender', models.CharField(max_length=255, verbose_name='性别')),
                ('address', models.CharField(max_length=255, verbose_name='现居地')),
                ('phone', models.CharField(max_length=255, verbose_name='电话')),
                ('identity', models.CharField(max_length=255, verbose_name='身份')),
                ('relation', models.CharField(max_length=255, verbose_name='关系')),
                ('hobby', models.CharField(max_length=255, verbose_name='爱好')),
                ('company', models.CharField(max_length=255, verbose_name='公司')),
                ('personality', models.CharField(max_length=255, verbose_name='性格')),
                ('correlation_degree', models.CharField(max_length=255, verbose_name='关联度')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='归属用户')),
            ],
        ),
    ]
