# Generated by Django 5.0.2 on 2024-03-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PasswordManageSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordinfo',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='名称'),
        ),
    ]
