# Generated by Django 5.0.2 on 2024-03-11 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PasswordManageSystem', '0002_alter_passwordinfo_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordinfo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_info', to=settings.AUTH_USER_MODEL, verbose_name='归属用户'),
        ),
    ]
