# Generated by Django 5.0.1 on 2024-04-09 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CookbookManageSystem', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
